_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 6
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 6
                - 41
                - 53
                - 55
            "3":
                - 1
                - 16
                - 23
                - 24
                - 55
            "4": 3.10.16
            "5": 0.19.5
            "8":
                - 1
                - 5
            "12": 0.19.5
            "13": linux-aarch64
lr:
    value: 0.0001
weight_decay:
    value: 1e-05
